from github import Github
from config import GITHUB_TOKEN

client = Github(GITHUB_TOKEN)

def post_review_comment(repo_name: str, pr_number: int, review: str):
    """Post the AI review as a comment on the GitHub PR."""

    print(f"Posting review to PR #{pr_number} in {repo_name}...")

    # 1. Get the repo object
    repo = client.get_repo(repo_name)

    # 2. Get the PR object
    pr = repo.get_pull(pr_number)

    # 3. Format the comment nicely
    comment = f"""##  PRReviewer — Automated Code Review

{review}

---
*Generated by PRReviewer using RAG + Llama 3.3 70B*
"""

    # 4. Post it as a PR comment
    pr.create_issue_comment(comment)

    print(f" Review posted successfully!")